# Generated by Django 3.1.6 on 2021-04-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('rut', models.CharField(max_length=9)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Lanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='numero de serie')),
                ('modelo', models.CharField(default='', max_length=20)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreID', models.CharField(default=None, max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('estado', models.CharField(choices=[('mesófila', 'Fase I: mesófila'), ('termófila', 'Fase II: termófila'), ('enfriamiento', 'Fase III: enfriamiento'), ('maduración', 'Fase IV: maduración')], max_length=50)),
                ('posicion', models.CharField(max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Fotos')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('predio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.predio')),
            ],
            options={
                'ordering': ('cliente',),
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('temperatura', models.IntegerField(default=0)),
                ('humedad', models.IntegerField(null=True)),
                ('lanza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.lanza')),
                ('pila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pila')),
            ],
            options={
                'verbose_name_plural': 'Mediciones',
                'ordering': ('lanza',),
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=10, null=True)),
                ('pila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pila')),
            ],
            options={
                'verbose_name_plural': 'Materias Primas',
                'ordering': ('nombre',),
            },
        ),
    ]
