# Generated by Django 3.1.6 on 2021-04-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pila',
            name='foto',
        ),
        migrations.AddField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos'),
        ),
    ]
